# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20190923_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='neg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='pos',
            field=models.FloatField(null=True),
        ),
    ]
